import { apiClient, unwrap } from './client';

export const adminApi = {
  getDashboard: () => unwrap(apiClient.get('/api/admin/dashboard')),
  refreshDashboard: () => unwrap(apiClient.post('/api/admin/dashboard/refresh')),
  getRequests: () => unwrap(apiClient.get('/api/admin/requests')),
  assignCompany: (requestId, payload) => unwrap(apiClient.put(`/api/admin/requests/${requestId}/assign-company`, payload)),
  getAccounts: () => unwrap(apiClient.get('/api/admin/accounts')),
  getAccount: (id) => unwrap(apiClient.get(`/api/admin/accounts/${id}`)),
  createAccount: (payload) => unwrap(apiClient.post('/api/admin/accounts', payload)),
  updateAccount: (id, payload) => unwrap(apiClient.put(`/api/admin/accounts/${id}`, payload)),
  deleteAccount: (id) => unwrap(apiClient.delete(`/api/admin/accounts/${id}`)),
  blockAccount: (id) => unwrap(apiClient.put(`/api/admin/accounts/${id}/block`)),
  unblockAccount: (id) => unwrap(apiClient.put(`/api/admin/accounts/${id}/unblock`)),
  getRoles: () => unwrap(apiClient.get('/api/admin/roles')),
  createRole: (payload) => unwrap(apiClient.post('/api/admin/roles', payload)),
  updateRole: (id, payload) => unwrap(apiClient.put(`/api/admin/roles/${id}`, payload)),
  deleteRole: (id) => unwrap(apiClient.delete(`/api/admin/roles/${id}`)),
  getIncidentTypes: () => unwrap(apiClient.get('/api/admin/incident-types')),
  createIncidentType: (payload) => unwrap(apiClient.post('/api/admin/incident-types', payload)),
  updateIncidentType: (id, payload) => unwrap(apiClient.put(`/api/admin/incident-types/${id}`, payload)),
  deleteIncidentType: (id) => unwrap(apiClient.delete(`/api/admin/incident-types/${id}`)),
  getServiceTypes: () => unwrap(apiClient.get('/api/admin/service-types')),
  createServiceType: (payload) => unwrap(apiClient.post('/api/admin/service-types', payload)),
  updateServiceType: (id, payload) => unwrap(apiClient.put(`/api/admin/service-types/${id}`, payload)),
  deleteServiceType: (id) => unwrap(apiClient.delete(`/api/admin/service-types/${id}`)),
  getCompanies: () => unwrap(apiClient.get('/api/admin/companies')),
  getCompany: (id) => unwrap(apiClient.get(`/api/admin/companies/${id}`)),
  createCompany: (payload) => unwrap(apiClient.post('/api/admin/companies', payload)),
  updateCompany: (id, payload) => unwrap(apiClient.put(`/api/admin/companies/${id}`, payload)),
  deleteCompany: (id) => unwrap(apiClient.delete(`/api/admin/companies/${id}`)),
  getCompanyStaff: (companyId) => unwrap(apiClient.get(`/api/admin/companies/${companyId}/staff`)),
  createCompanyStaff: (companyId, payload) => unwrap(apiClient.post(`/api/admin/companies/${companyId}/staff`, payload)),
  updateCompanyStaff: (companyId, staffId, payload) => unwrap(apiClient.put(`/api/admin/companies/${companyId}/staff/${staffId}`, payload)),
  deleteCompanyStaff: (companyId, staffId) => unwrap(apiClient.delete(`/api/admin/companies/${companyId}/staff/${staffId}`)),
};
